### ISSUE TITLE
Project-Trident website error

### ISSUE THREAD

**Issue by ZoltanHegedus** [project-trident/trident-website#37]
From the community:

https://www.ixsystems.com/community/threads/project-trident-website-error.77371/

**Comment by beanpole135** [comment]
Ok, I think this is fixed now: https://github.com/project-trident/trident-website/commit/d562b9fc08df3c0e130492336bec4c76c0a76011

It looks like the PayPal badge was loading really slowly from the PayPal object CDN. I just removed that badge from the menu and replaced it with a button to open the sponsors page instead.

**Comment by ZoltanHegedus** [comment]
Sorry, I'm trying every day and the problem is still there. Try more times to click on different element of the site. About from 5-10 click one will reproduce the problem. Sorry.

**Comment by ZoltanHegedus** [comment]
Now the website works hundred percent perfectly. Solved.
